### PR TITLE
intial scaffold

### PR DESCRIPTION
**Pull request by lburgazzoli**

### CODE REVIEW

**Comment by lgarciaaco** [comment]
@lburgazzoli i am trying to understand the project structure, did you create the it using the operator-sdk? If I follow https://sdk.operatorframework.io/docs/building-operators/golang/quickstart/  I end up with a different structure.

```
$ operator-sdk version
operator-sdk version: "v1.31.0", commit: "e67da35ef4fff3e471a208904b2a142b27ae32b1", kubernetes version: "v1.26.0", go version: "go1.20.6", GOOS: "darwin", GOARCH: "amd64"
```

**Comment by lburgazzoli** [comment]
@lgarciaaco no it is based on the upstream kubebuilder [1][2] as operator-sdk embeds it but it is always behind it and I want to leverage new features as soon as they are available upstream.  Generating OLM bundles is a matter of piping the kustomize build output to operator-sdk, i.e. what we did for the cos [3]

1. https://book.kubebuilder.io/
2. https://github.com/kubernetes-sigs/kubebuilder
3. https://github.com/bf2fc6cc711aee1a0c2a/cos-manifests/blob/main/hack/bundle.sh

**Comment by lburgazzoli** [comment]
@rinaldodev @lgarciaaco have you had any time to look at this ? this is nothing more than an initial scaffolding of the project, there is no coded behavior, reconcile logic. Just some code to have something to start from.

**Comment by lgarciaaco** [comment]
Yes @lburgazzoli I had the time to run it locally it looks good to me. There is some code that is not used but I am guessing it was autogenerated I am also fine with it. I think this is a good starting point for SCO-24

**Review by lgarciaaco — APPROVED** [review]

**Comment by lburgazzoli** [comment]
yep the code is from the kaoto operator that I was working on so there may be some leftover and some unused code

**Pull request merged**
